### ISSUE TITLE
Aftman fails to install tools

### ISSUE THREAD

**Issue by AridDev** [ok-nick/setup-aftman#9]
![image](https://github.com/ok-nick/setup-aftman/assets/118916772/ec291f0e-79fd-44a1-9f81-73ee277b2b40)
It says that rojo was not installed before and asking me if I want to install it. I later tried `aftman trust` as well. Doesn't work.

I also tried using `aftman.toml` file to install the tools, which doesn't show any errors in this part. However, when I try to run it, it just spits out `rojo: command cannot be found`

![image](https://github.com/ok-nick/setup-aftman/assets/118916772/93686c67-05fe-450b-8a17-cecc323cecef)

**Comment by ok-nick** [comment]
What versions of `setup-aftman` and `aftman` are you using? Can you send a snippet of your code?

**Comment by AridDev** [comment]
![image](https://github.com/ok-nick/setup-aftman/assets/118916772/340a053a-92c3-452f-bc9a-4841eec4ea27)
![image](https://github.com/ok-nick/setup-aftman/assets/118916772/6e081830-a2b0-4ca5-b469-5c87313840ef)

**Comment by ok-nick** [comment]
Try two things:
1. Try removing manually passing the token (it's automatically fetched by default)
2. Try using an `aftman.toml` file instead of manually adding and installing the tools

**Comment by AridDev** [comment]
> 1. Try removing manually passing the token (it's automatically fetched by default)
I don't think that has anything to do with it. The problem isn't in fetching the tools. It's in installing the tools itself.

> 2. Try using an `aftman.toml` file instead of manually adding and installing the tools

Already tried this. When I do this, the installation error doesn't come up, but when running the tools itself, like rojo / rbxcloud, it throws an error like `rojo: command not found`.

**Comment by ok-nick** [comment]
https://github.com/rojo-rbx/rojo/actions/runs/5677456916/job/15385801017

Is your output similar to `rojo`s logs? It should say `Installing ...` and `Downloading ...` for each tool.

**Comment by AridDev** [comment]
It doesn't. This is what it says if I use `aftman add [...]` and then `aftman install`

![image](https://github.com/ok-nick/setup-aftman/assets/118916772/5b37ab35-57de-4b4b-a45c-ee42ad8b2f08)

And when I use the file, the installation part has no errors, but it doesn't install the tools.
![image](https://github.com/ok-nick/setup-aftman/assets/118916772/0a53793a-b577-4baa-bef1-173bb2356670)

**Comment by ok-nick** [comment]
When using the `aftman.toml` file, are you sure it exists and is in the top-level directory? Try adding the command `cat aftman.toml`.

**Comment by AridDev** [comment]
Tried, but it does absolutely nothing..

**Comment by ok-nick** [comment]
Are you using `actions/checkout` and positive that your project is being installed correctly? Considering the `aftman.toml` is in your project, the command should've returned the file contents.

Try using the `ls` command as well to make sure everything is being installed.

**Comment by AridDev** [comment]
Rn not on my PC but will let you know as soon as I get on!

**Comment by AridDev** [comment]
Okay. I opened a new repo and it seems like it works over there. I don't what happened. I didn't do much modifications to the code itself.

```yaml
name: Deploy to Staging

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: ok-nick/setup-aftman@v0.3.0
        name: Install aftman
        with:
          token: ${{ SECRETS.GITHUB_TOKEN }}

      - run: |
          rojo build -o game.rbxl
          rbxcloud experience publish -f game.rbxl -p 14072856068 -u 4035961123 -t published -a ${{ secrets.API_KEY }}
```

This one works and I just changed up how me and my friends are gonna work on the game so I hope it won't be a problem. There's one thing though.

I can see the new progress using the explorer feature of BTRoblox.
![image](https://github.com/ok-nick/setup-aftman/assets/118916772/d447b89c-5920-49b0-ad13-97f41b94661e)


But I don't see the progress on studio itself:
![image](https://github.com/ok-nick/setup-aftman/assets/118916772/8d2307e8-a6b6-468c-a81b-d7d77716127e)

Is there anything I need to fetch or what? Or like wait in progress? Either way, thank you for the help. Really appreciated!
